name: Front-end CI/CD
on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - 'application/frontend/**' 
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
        run:
          working-directory: ./application/frontend/

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Build
      run: npm run build

    - name: Deploy to Skynet
      uses: kwypchlo/deploy-to-skynet-action@main
      with:
        upload-dir: ./application/frontend/build
        github-token: ${{ secrets.GITHUB_TOKEN }}
        registry-seed: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.REGISTRY_SEED || '' }}
